# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_by', models.CharField(default=False, max_length=40)),
                ('commented_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('commenter_mail_id', models.EmailField(default=False, max_length=40)),
                ('comment_text', models.CharField(default=False, max_length=300)),
            ],
            options={
                'ordering': ['-commented_on'],
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_url', models.CharField(default=False, max_length=50)),
                ('post_head', models.CharField(default=False, max_length=50)),
                ('post_text', models.TextField(default=False, max_length=5000)),
                ('post_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_likes', models.IntegerField(default=0)),
                ('post_views', models.IntegerField(default=0)),
                ('post_shares', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-post_created_on'],
            },
        ),
        migrations.CreateModel(
            name='Tagging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_tag', models.CharField(max_length=30)),
                ('color_choice', models.CharField(choices=[('bg-red', 'red'), ('bg-yellow', 'yellow'), ('bg-aqua', 'aqua'), ('bg-blue', 'blue'), ('bg-light blue', 'light-blue'), ('bg-green', 'green'), ('bg-navy', 'navy'), ('bg-teal', 'teal'), ('bg-olive', 'olive'), ('bg-lime', 'lime'), ('bg-orange', 'orange'), ('bg-fuchsia', 'fuchsia'), ('bg-purple', 'purple'), ('bg-maroon', 'maroon'), ('bg-black', 'black'), ('bg-red-archive', 'red-active'), ('bg-yellow-active', 'yellow-active'), ('bg-aqua-active', 'aqua-active'), ('bg-blue-active', 'blue-active'), ('bg-light-blue-active', 'light-blue-active'), ('bg-green-active', 'green-active'), ('bg-navy-active', 'navy-active'), ('bg-teal-active', 'teal-active'), ('bg-olive-active', 'olive-active'), ('bg-lime-active', 'lime-active'), ('bg-orange-active', 'orange-active'), ('bg-fuchsia-active', 'fuchsia-active')], default='.bg-red', max_length=30)),
                ('post_of_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Posts')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='post_commented',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Posts'),
        ),
    ]
