# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=False, max_length=40)),
                ('email_id', models.CharField(default=False, max_length=50)),
                ('phone_no', models.CharField(default=False, max_length=12)),
                ('message', models.TextField(default=False, max_length=100)),
                ('time_sent', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-time_sent'],
            },
        ),
    ]
